### ISSUE TITLE
New request!

### ISSUE THREAD

**Issue by marcosllinares** [autohub7/obsidian-tab-rotator#1]
New request so that the tab rotator does not remain automatically rotating but rather so that it only advances one tab for shortcut activation. Thankss

**Comment by autohub7** [comment]
@marcosllinares Without using this Plugin, moving to the next tab is possible with a shortcut.


Go to the next tab: Control-Tab (Windows) or Shift-Command-] (MacOS)
Go to the previous tab: Control-Shift-Tab  (Windows) or Shift-Command-[ (MacOS)

**Comment by marcosllinares** [comment]
@autohub7 oh wow im such a noob, thank you anyways!
